# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: local

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet publish PowerSupplySystemApi --configuration Release --output publish/
  displayName: Packing application PowerSupplySystemApi

- task: CopyFiles@2
  displayName: Copy packed application WebApp to output
  inputs:
    contents: |
      PowerSupplySystemApi/publish/**
      !**/appsettings.Development.json
    targetFolder: '$(Build.ArtifactStagingDirectory)/'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publishing artifacts