// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RA.PowerSupplySystem.Persistence.DatabaseContext;

#nullable disable

namespace RA.PowerSupplySystem.Persistence.Migrations
{
    [DbContext(typeof(RaDatabaseContext))]
    [Migration("20230827234930_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RA.PowerSupplySystem.Domain.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Resistencia de 10k Ohms",
                            Name = "Resistencia",
                            PartNumber = "R10K",
                            Stock = 1000
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tablero de circuito impreso",
                            Name = "Tablero",
                            PartNumber = "PCB4",
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Carcasa para fuente de poder",
                            Name = "Carcasa",
                            PartNumber = "CARK",
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "Capacitor de 22 uF",
                            Name = "Capacitor",
                            PartNumber = "C22U",
                            Stock = 1000
                        });
                });

            modelBuilder.Entity("RA.PowerSupplySystem.Domain.MaterialEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Batch = "c256530b-adfc-4006-916a-3120933895f1",
                            EntryDate = new DateTime(2023, 8, 27, 16, 49, 30, 541, DateTimeKind.Local).AddTicks(9813),
                            MaterialId = 1,
                            Quantity = 1000
                        },
                        new
                        {
                            Id = 2,
                            Batch = "410bef14-6e7b-4714-ac3b-32c67de86c38",
                            EntryDate = new DateTime(2023, 8, 27, 16, 49, 30, 541, DateTimeKind.Local).AddTicks(9861),
                            MaterialId = 2,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 3,
                            Batch = "8b82b18b-1293-43e7-8e9e-ecbab8336081",
                            EntryDate = new DateTime(2023, 8, 27, 16, 49, 30, 541, DateTimeKind.Local).AddTicks(9864),
                            MaterialId = 3,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 4,
                            Batch = "f50d6f6d-7942-4d2f-b586-22df1889b858",
                            EntryDate = new DateTime(2023, 8, 27, 16, 49, 30, 541, DateTimeKind.Local).AddTicks(9865),
                            MaterialId = 4,
                            Quantity = 1000
                        });
                });

            modelBuilder.Entity("RA.PowerSupplySystem.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RA.PowerSupplySystem.Domain.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("RA.PowerSupplySystem.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fuente de poder de 24 Volts",
                            Name = "Fuente 24V",
                            Price = 400m
                        });
                });

            modelBuilder.Entity("RA.PowerSupplySystem.Domain.ProductMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMaterials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaterialId = 1,
                            ProductId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            MaterialId = 2,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            MaterialId = 3,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            MaterialId = 4,
                            ProductId = 1,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("RA.PowerSupplySystem.Domain.MaterialEntry", b =>
                {
                    b.HasOne("RA.PowerSupplySystem.Domain.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("RA.PowerSupplySystem.Domain.OrderDetail", b =>
                {
                    b.HasOne("RA.PowerSupplySystem.Domain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RA.PowerSupplySystem.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RA.PowerSupplySystem.Domain.ProductMaterial", b =>
                {
                    b.HasOne("RA.PowerSupplySystem.Domain.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RA.PowerSupplySystem.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
